#!/bin/bash
: ${PREFIX:=/usr/local}
. "$PREFIX/etc/dlite.conf"

: ${DLITE_CPUS:=1}
: ${DLITE_MEM:=1G}

get_ip() {
    awk '
    {
      if ($1 ~ /^name/) {
        name=substr($1, 6)
      }
      if ($1 ~ /^ip_address/) {
        ip_address=substr($1, 12)
      }
      if (name != "" && ip_address != "") {
        ip_addresses[name]=ip_address
        name=ip_address=""
      }
    }
    END {
        print ip_addresses["'$DLITE_UUID'"]
    }
    ' /var/db/dhcpd_leases
}

mkdir -p "$PREFIX/var/log"
"$XHYVE" -A -c $DLITE_CPUS -m $DLITE_MEM -s 0:0,hostbridge -l com1,stdio -s 31,lpc -s 2:0,virtio-net -s 4,virtio-blk,"$PREFIX/var/db/dlite/disk.img" -U $DLITE_UUID -f kexec,"$PREFIX/usr/share/dlite/bzImage","$PREFIX/usr/share/dlite/rootfs.cpio.xz","console=ttyS0 hostname=dlite uuid=$DLITE_UUID" >"$PREFIX/var/log/dlite.log" 2>&1 &
XHYVE_PID=$!

IP=$(get_ip)
until [ -n "$IP" ]; do
    IP=$(get_ip)
    sleep 1
done

echo "$IP local.docker # created by dlite" >> /etc/hosts
"$SOCAT" -t600 unix-listen:/var/run/docker.sock,mode=777,reuseaddr,fork tcp:$IP:2375,keepalive,end-close &
SOCAT_PID=$!
until [ -e "/var/run/docker.sock" ]; do
    sleep 1
done

cleanup() {
    kill $XHYVE_PID >/dev/null 2>&1
    while ps $XHYVE_PID >/dev/null 2>&1; do
        sleep 1
    done

    kill -9 $SOCAT_PID >/dev/null 2>&1
    rm -f /var/run/docker.sock
    sed -i '' '/.*# created by dlite/d' /etc/hosts
}

trap cleanup EXIT

# keep us running
while true; do
    sleep 30
done
