#!/bin/bash

: ${PREFIX:=/usr/local}

if [ "$USER" != "root" ]; then
    sudo "$0"
    exit $?
fi

echo -n "removing launchd daemon.."
launchctl stop local.dlite >/dev/null 2>&1
launchctl unload /Library/LaunchDaemons/local.dlite.plist >/dev/null 2>&1
rm -f /Library/LaunchDaemons/local.dlite.plist
echo "done"

echo -n "removing vm.."
rm -rf "$PREFIX/usr/share/dlite"
echo "done"

echo -n "removing disk image.."
rm -rf "$PREFIX/var/db/dlite"
echo "done"

echo -n "removing configuration.."
rm -f "$PREFIX/etc/dlite.conf"
echo "done"

echo -n "removing dlite.."
rm -f "$PREFIX/bin/dlite"
echo "done"
